# NSL-KDD Dataset Configuration
# Generated by setup_kaggle_data.py

TRAIN_FILE = "data/NSL-KDD\KDDTrain+_20Percent.txt"
TEST_FILE = "data/NSL-KDD\KDDTest+.txt"

# Available files:
# KDDTrain+.txt: data/NSL-KDD\KDDTrain+.txt
# KDDTest+.txt: data/NSL-KDD\KDDTest+.txt
# KDDTrain+_20Percent.txt: data/NSL-KDD\KDDTrain+_20Percent.txt
